### ISSUE TITLE
seems not work

### ISSUE THREAD

**Issue by huanzhang** [KJlmfe/Alfred-workflows#1]
alt+space然后输入zh 直呼

显示“正在努力搜索”后就变成了google搜索了。

**Comment by mbli** [comment]
debug了一下，request地址http://www.zhihu.com/autocomplete?max_matches=10&use_similar=0&token= 时知乎返回了403 Forbitten，不过浏览器直接访问这个地址正常，可能是请求headers不完整被知乎拒绝了

**Comment by huanzhang** [comment]
确实，浏览器有返回结果

**Comment by kadovat** [comment]
跟了一下，headers少了User-Agent，加上后可以正常使用

**Comment by huanzhang** [comment]
👍

**Comment by mbli** [comment]
确实，改一行代码：
$data = $wf->request( "http://www.zhihu.com/autocomplete?max_matches=10&use_similar=0&token=".urlencode( $orig ), array(CURLOPT_USERAGENT => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9") );

**Comment by Exvoke** [comment]
你好，修改代码之后问题依旧，请问有解决方案么？

**Comment by kadovat** [comment]
http重定向到https了，curl会返回一个301，手动改成https就可以了

把info.plist里的
$zh_url = "http://www.zhihu.com";
改为
$zh_url = "https://www.zhihu.com";

$data = $wf-&gt;request( "http://www.zhihu.com/autocomplete?max_matches=10&amp;use_similar=0&amp;token=".urlencode( $orig ) );
改为
$data = $wf-&gt;request( "https://www.zhihu.com/autocomplete?max_matches=10&amp;use_similar=0&amp;token=".urlencode( $orig ) );

**Comment by Exvoke** [comment]
感谢！问题解决，这是一个很方便的workflow！感谢维护

**Comment by KJlmfe** [comment]
@kadovat 谢谢，我这边已经按照你的方法修复了
