### ISSUE TITLE
知乎日报不能正常加载

### ISSUE THREAD

**Issue by faketerigo** [KJlmfe/Alfred-workflows#2]
输入关键字后会直接跳转到搜索界面

**Comment by KJlmfe** [comment]
@faketerigo 已经修复了，你重新下载后，再试试

**Comment by faketerigo** [comment]
还是有同样的问题，是否需要其他的设置？

**Comment by KJlmfe** [comment]
是从Master分支重新下载导入的吗？

可以截图发我下你在alfred里输入的命令么？

faketerigo <notifications@github.com>于2017年12月6日 周三22:33写道：
